version: '2'

services:
  my_proxy:
    image: 'nginx_pkg:latest'
    container_name: my_proxy
    ports:
      - '8084:80'
    volumes:
      - './conf/proxy.conf:/etc/nginx/conf.d/default.conf'
    networks:
      nginx_network:
        aliases:
          - my_proxy

  my_loadbalancer:
    image: 'nginx_pkg:latest'
    container_name: my_loadbalancer
    ports:
      - '8083:80'
    volumes:
      - './conf/lb.conf:/etc/nginx/conf.d/default.conf'
      - './nginx_loadbalancer_logs:/var/log/nginx'
    networks:
      nginx_network:
        aliases:
          - my_loadbalancer
    links:
      - my_proxy

  my_nginx_01:
    image: 'nginx_pkg:latest'
    container_name: my_nginx_01
    ports:
      - '8081:80'
    volumes:
      - './conf/nginx01/index.html:/usr/share/nginx/html/index.html'
    networks:
      nginx_network:
        aliases:
          - my_nginx_01
    links:
      - my_proxy

  my_nginx02:
    image: 'nginx_pkg:latest'
    container_name: my_nginx_02
    ports:
      - '8082:80'
    volumes:
      - './conf/nginx02/index.html:/usr/share/nginx/html/index.html'
    networks:
      nginx_network:
        aliases:
          - my_nginx_02
    links:
      - my_proxy

networks:
  nginx_network:
    driver: bridge
